CREATE TABLE leituras_sensores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    temperatura DECIMAL(5, 2) NOT NULL,
    umidade DECIMAL(5, 2) NOT NULL,
    luminosidade INT NOT NULL,
    leitura_potenciometro INT NOT NULL, 
    botao_pressionado BOOLEAN NOT NULL,
    data_hora TIMESTAMPTZ DEFAULT NOW()
);

-- Desativa RLS na tabela
ALTER TABLE leituras_sensores DISABLE ROW LEVEL SECURITY;