// Code generated by Arduino IoT Cloud - MODIFICADO para incluir credenciais direto
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "3c4cd654-bc99-4e34-bd3e-adbf5236d103";

const char SSID[]        = "Pedro's Galaxy M14 5G";  // sua rede WiFi
const char PASS[]        = "12345678";                // sua senha WiFi
const char DEVICE_KEY[]  = "X2atmjc5suAnEpM59Lq?512xM";    // ← SUBSTITUA pela Secret Key do device Audrey

void onComandoChange();
void onTemperaturaChange();
void onUmidadeChange();
void onLuminosidadeChange();
void onPotenciometroChange();
void onSistemaAtivoChange();

String  comando;
float   Temperatura;
float   Umidade;
int     Luminosidade;
int     Potenciometro;
bool    sistemaAtivo;

void initProperties() {
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(comando,       READWRITE, ON_CHANGE, onComandoChange);
  ArduinoCloud.addProperty(Temperatura,   READWRITE, ON_CHANGE, onTemperaturaChange);
  ArduinoCloud.addProperty(Umidade,       READWRITE, ON_CHANGE, onUmidadeChange);
  ArduinoCloud.addProperty(Luminosidade,  READWRITE, ON_CHANGE, onLuminosidadeChange);
  ArduinoCloud.addProperty(Potenciometro, READWRITE, ON_CHANGE, onPotenciometroChange);
  ArduinoCloud.addProperty(sistemaAtivo,  READWRITE, ON_CHANGE, onSistemaAtivoChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);